title: Your Name
subtitle: Software Developer
description: Developer portfolio
url: https://FGiacomo.github.io
root: /
theme: cactus

deploy:
  type: git
  repo: https://github.com/FGiacomo/FGiacomo.github.io.git
  branch: gh-pages
